server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=0
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=0
        - id: eureka-service
          uri: lb://eureka-service
          predicates:
            - Path=/api/services/**
          filters:
            - StripPrefix=0
        - id: eureka-dashboard
          uri: lb://eureka-service
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0
        - id: integration-service
          uri: lb://api-gateway
          predicates:
            - Path=/api/integration/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
